// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ8Nq2nNilQwvfCRho-EIdy2P5IDE2Fao',
    appId: '1:446158493942:web:bc20a3190d84e8d74734d7',
    messagingSenderId: '446158493942',
    projectId: 'smart-dustbin-app-67e52',
    authDomain: 'smart-dustbin-app-67e52.firebaseapp.com',
    databaseURL: 'https://smart-dustbin-app-67e52-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-dustbin-app-67e52.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKEfBr5U2Ok6KxNxflXP44v164n_T9WGc',
    appId: '1:446158493942:android:7e775b729a123f594734d7',
    messagingSenderId: '446158493942',
    projectId: 'smart-dustbin-app-67e52',
    databaseURL: 'https://smart-dustbin-app-67e52-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-dustbin-app-67e52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6NIkYwpGA_O-5HqKQ_Ah1_oTP4EAqfHU',
    appId: '1:446158493942:ios:8c7d4cd711d0e3814734d7',
    messagingSenderId: '446158493942',
    projectId: 'smart-dustbin-app-67e52',
    databaseURL: 'https://smart-dustbin-app-67e52-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-dustbin-app-67e52.firebasestorage.app',
    iosBundleId: 'com.example.flutterCapstoneProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6NIkYwpGA_O-5HqKQ_Ah1_oTP4EAqfHU',
    appId: '1:446158493942:ios:8c7d4cd711d0e3814734d7',
    messagingSenderId: '446158493942',
    projectId: 'smart-dustbin-app-67e52',
    databaseURL: 'https://smart-dustbin-app-67e52-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-dustbin-app-67e52.firebasestorage.app',
    iosBundleId: 'com.example.flutterCapstoneProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ8Nq2nNilQwvfCRho-EIdy2P5IDE2Fao',
    appId: '1:446158493942:web:e4bfbf3e97398aac4734d7',
    messagingSenderId: '446158493942',
    projectId: 'smart-dustbin-app-67e52',
    authDomain: 'smart-dustbin-app-67e52.firebaseapp.com',
    databaseURL: 'https://smart-dustbin-app-67e52-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-dustbin-app-67e52.firebasestorage.app',
  );
}
